from setuptools import setup, find_packages 
import io

setup(	name='mantis_ml',
	version='1.5',
	author='Dimitrios Vitsios',
	author_email='dvitsios@gmail.com',
	description='Disease-agnostic gene prioritisation from high-throughput genomic screens by stochastic semi-supervised learning',
	url="https://github.com/astrazeneca-cgr-publications/mantis-ml-release",
	packages=find_packages(),
	python_requires='>=3.6',
	install_requires=['numpy==1.14.5',
			  'numpydoc==0.8.0',
			  'pandas==0.24.2',
 			  'scipy==1.2.1',
			  'scikit-learn==0.20.3',
		    	  'bokeh==1.1.0',
			  'h5py==2.9.0',
			  'tensorflow==1.10.0',
			  'Keras==2.2.4',
			  'matplotlib==3.0.3',
			  'palettable==3.1.1',
			  'plotly==3.9.0',
			  'PyYAML==5.1',
			  'seaborn==0.9.0',
			  'tables==3.5.1',
			  'umap-learn==0.3.8',
			  'xgboost==0.80'],
	package_data={'mantis_ml': [ 'data/*',
				     'data/exSNP/*',
				     'data/gwas_catalog/*',
				     'data/gnomad/*',
				     'data/goa/*',
				     'data/mgi/*',
				     'data/ensembl/*',
				     'data/platelets_eqtl/*',
				     'data/in_web/*',
				     'data/rvis_plosgen_2013/*',
				     'data/neph_qtl/*',
				     'data/omim/*',
				     'data/ckddb/*',
				     'data/adipose_eqtl/*',
				     'data/HPO/*',
				     'data/genic-intolerance/*',
				     'data/human_protein_atlas/*',
				     'data/exac-broadinstitute/*',
				     'data/exac-broadinstitute/cnv/*',
				     'data/essential_genes_for_mouse/*',
				     'data/random_vs_seed-mantis_ml_scores/CKD/*',
				     'data/random_vs_seed-mantis_ml_scores/Epilepsy/*',
				     'data/random_vs_seed-mantis_ml_scores/ALS/*',
				     'data/msigdb/tables_per_gene_set/*',
				     'data/gtex/RNASeq/*',
				     'modules/supervised_learn/feature_selection/boruta_feature_selection.R',
				     'conf/.config',
				     'conf/*']},
	include_package_data=True,
	entry_points={'console_scripts': ['mantisml=mantis_ml.modules.main.__main__:main',
					  'mantisml-profiler=mantis_ml.modules.profiler.__main__:main',
					  'mantisml-overlap=mantis_ml.modules.hypergeom_enrichment.__main__:main']}
)
